import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { User, UserActivity, Student } from '@/types';

const DKTE_LOGO_URL = 'https://miaoda-conversation-file.s3cdn.medo.dev/user-845wqo7mn94w/conv-845wum9wqhog/20251210/file-852rchre4v0g.png';

export type ReportType =
  | 'all_users'
  | 'students_department'
  | 'staff_department'
  | 'department_consolidated'
  | 'role_wise'
  | 'login_activity';

export interface ReportFilters {
  department?: string;
  role?: string;
  dateFrom?: string;
  dateTo?: string;
}

export interface ReportData {
  reportType: ReportType;
  users: User[];
  students: Student[];
  activities: UserActivity[];
  filters: ReportFilters;
  generatedBy: string;
}

const loadImageAsBase64 = async (url: string): Promise<string> => {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error('Error loading image:', error);
    return '';
  }
};

const formatDateTime = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
};

const formatDate = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
};

const getRoleDisplayName = (role: string): string => {
  const roleNames: Record<string, string> = {
    admin: 'Administrator',
    student: 'Student',
    teacher: 'Teacher',
    hod: 'HOD',
    library: 'Library',
    accounts: 'Accounts',
    scholarship: 'Scholarship',
    student_section: 'Student Section',
    hostel_bus: 'Hostel/Bus',
    tpo: 'Training & Placement',
    exam_cell: 'Exam Cell',
  };
  return roleNames[role] || role;
};

const formatDuration = (minutes?: number): string => {
  if (!minutes) return 'N/A';
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  if (hours > 0) {
    return `${hours} hr ${mins} min`;
  }
  return `${mins} min`;
};

const getRoleSortOrder = (role: string): number => {
  const order: Record<string, number> = {
    admin: 1,
    hod: 2,
    teacher: 3,
    library: 4,
    accounts: 5,
    scholarship: 6,
    student_section: 7,
    hostel_bus: 8,
    tpo: 9,
    exam_cell: 10,
    student: 11,
  };
  return order[role] || 99;
};

const addHeader = async (
  doc: jsPDF,
  title: string,
  yPosition: number
): Promise<number> => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = yPosition;

  try {
    const logoBase64 = await loadImageAsBase64(DKTE_LOGO_URL);
    if (logoBase64) {
      const logoWidth = 50;
      const logoHeight = 13.4;
      const logoX = (pageWidth - logoWidth) / 2;
      doc.addImage(logoBase64, 'PNG', logoX, y, logoWidth, logoHeight);
      y += logoHeight + 5;
    }
  } catch (error) {
    console.error('Error adding logo:', error);
    y += 5;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(0, 51, 102);
  const collegeName = "DKTE SOCIETY'S YASHWANTRAO CHAVAN POLYTECHNIC";
  doc.text(collegeName, pageWidth / 2, y, { align: 'center' });
  y += 7;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0, 102, 51);
  doc.text(title, pageWidth / 2, y, { align: 'center' });
  y += 3;

  doc.setDrawColor(0, 102, 51);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  return y;
};

const addMetadata = (
  doc: jsPDF,
  data: ReportData,
  yPosition: number,
  additionalInfo?: Record<string, string>
): number => {
  const margin = 15;
  let y = yPosition;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);

  const metaData: [string, string][] = [
    ['Report Type:', getReportTypeName(data.reportType)],
    ['Generated By:', data.generatedBy],
    ['Generated On:', formatDateTime(new Date().toISOString())],
  ];

  if (data.filters.department) {
    metaData.push(['Department:', data.filters.department]);
  }
  if (data.filters.role) {
    metaData.push(['Role Filter:', getRoleDisplayName(data.filters.role)]);
  }
  if (data.filters.dateFrom || data.filters.dateTo) {
    const dateRange = `${data.filters.dateFrom ? formatDate(data.filters.dateFrom) : 'Start'} to ${data.filters.dateTo ? formatDate(data.filters.dateTo) : 'End'}`;
    metaData.push(['Date Range:', dateRange]);
  }

  if (additionalInfo) {
    Object.entries(additionalInfo).forEach(([key, value]) => {
      metaData.push([key, value]);
    });
  }

  const labelWidth = 35;
  metaData.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, margin + labelWidth, y);
    y += 5;
  });

  return y + 3;
};

const addDeclarationAndSignature = (doc: jsPDF, yPosition: number): number => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  let y = yPosition;

  if (y > pageHeight - 80) {
    doc.addPage();
    y = margin;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(0, 51, 102);
  doc.text('Declaration', margin, y);
  y += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0);
  const declarationText =
    'This report is system-generated from the college management database and reflects real-time user information as of the report generation date.';
  const splitDeclaration = doc.splitTextToSize(declarationText, pageWidth - 2 * margin);
  doc.text(splitDeclaration, margin, y);
  y += splitDeclaration.length * 4 + 5;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(0, 51, 102);
  doc.text('Signature Section', margin, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0);

  const signatures = [
    'Prepared By: Admin (System Generated)',
    'Verified By: System Administrator',
    'Authorized Signatory: Principal / Registrar',
  ];

  signatures.forEach((sig) => {
    doc.text(sig, margin + 5, y);
    y += 5;
  });

  return y;
};

const addFooter = (doc: jsPDF): void => {
  const totalPages = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    const footerY = pageHeight - 10;
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);

    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text(
      'This is a system-generated document and does not require a physical signature.',
      pageWidth / 2,
      footerY,
      { align: 'center' }
    );

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, footerY + 3, { align: 'right' });
    doc.text('EduClera - College Management System', margin, footerY + 3, { align: 'left' });
  }
};

const getReportTypeName = (type: ReportType): string => {
  const names: Record<ReportType, string> = {
    all_users: 'All Users Report',
    students_department: 'Students - Department Wise',
    staff_department: 'Staff - Department Wise',
    department_consolidated: 'Department-Wise Consolidated Report',
    role_wise: 'Role-Wise Users Report',
    login_activity: 'Login & Activity Session Report',
  };
  return names[type];
};

const filterUsers = (users: User[], filters: ReportFilters): User[] => {
  let filtered = [...users];

  if (filters.department) {
    filtered = filtered.filter((u) => u.department === filters.department);
  }

  if (filters.role) {
    filtered = filtered.filter((u) => u.role === filters.role);
  }

  if (filters.dateFrom) {
    const fromDate = new Date(filters.dateFrom);
    filtered = filtered.filter((u) => new Date(u.createdAt) >= fromDate);
  }

  if (filters.dateTo) {
    const toDate = new Date(filters.dateTo);
    filtered = filtered.filter((u) => new Date(u.createdAt) <= toDate);
  }

  return filtered;
};

const generateAllUsersReport = async (data: ReportData): Promise<jsPDF> => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  let yPosition = margin;
  yPosition = await addHeader(doc, 'ALL USERS REPORT', yPosition);

  const filteredUsers = filterUsers(data.users, data.filters);
  yPosition = addMetadata(doc, data, yPosition, {
    'Total Users:': filteredUsers.length.toString(),
  });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 51, 102);
  doc.text('User Information', margin, yPosition);
  yPosition += 5;

  const sortedUsers = [...filteredUsers].sort((a, b) => {
    const orderA = getRoleSortOrder(a.role);
    const orderB = getRoleSortOrder(b.role);
    if (orderA !== orderB) return orderA - orderB;
    return a.name.localeCompare(b.name);
  });

  const tableData = sortedUsers.map((user, index) => {
    const activity = data.activities.find((a) => a.userId === user.id);
    return [
      (index + 1).toString(),
      user.name,
      user.username,
      getRoleDisplayName(user.role),
      user.department || '—',
      user.email,
      formatDate(user.createdAt),
      activity?.accountStatus || 'Inactive',
    ];
  });

  autoTable(doc, {
    startY: yPosition,
    head: [['Sr.', 'Name', 'Username', 'Role', 'Department', 'Email', 'Joined Date', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 51, 102],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [0, 0, 0],
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 10 },
      1: { halign: 'left', cellWidth: 28 },
      2: { halign: 'left', cellWidth: 22 },
      3: { halign: 'center', cellWidth: 22 },
      4: { halign: 'center', cellWidth: 22 },
      5: { halign: 'left', cellWidth: 32 },
      6: { halign: 'center', cellWidth: 20 },
      7: { halign: 'center', cellWidth: 14 },
    },
    margin: { left: margin, right: margin },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 10;
  yPosition = addDeclarationAndSignature(doc, yPosition);
  addFooter(doc);

  return doc;
};

const generateStudentsDepartmentReport = async (data: ReportData): Promise<jsPDF> => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const margin = 15;

  let yPosition = margin;
  const deptName = data.filters.department || 'All Departments';
  yPosition = await addHeader(
    doc,
    `STUDENT USER REPORT - ${deptName.toUpperCase()}`,
    yPosition
  );

  const studentUsers = filterUsers(
    data.users.filter((u) => u.role === 'student'),
    data.filters
  );

  const activeCount = data.activities.filter(
    (a) => studentUsers.some((u) => u.id === a.userId) && a.accountStatus === 'active'
  ).length;

  yPosition = addMetadata(doc, data, yPosition, {
    'Total Students:': studentUsers.length.toString(),
    'Active Students:': activeCount.toString(),
    'Inactive Students:': (studentUsers.length - activeCount).toString(),
  });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 51, 102);
  doc.text('Student Details', margin, yPosition);
  yPosition += 5;

  const tableData = studentUsers.map((user, index) => {
    const studentData = data.students.find((s) => s.userId === user.id);
    const activity = data.activities.find((a) => a.userId === user.id);
    return [
      (index + 1).toString(),
      user.name,
      studentData?.enrollmentNumber || 'N/A',
      user.username,
      user.email,
      studentData?.year?.toString() || 'N/A',
      formatDate(user.createdAt),
      activity?.accountStatus || 'Inactive',
    ];
  });

  autoTable(doc, {
    startY: yPosition,
    head: [['Sr.', 'Student Name', 'PRN', 'Username', 'Email', 'Year', 'Joined Date', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 51, 102],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [0, 0, 0],
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 10 },
      1: { halign: 'left', cellWidth: 30 },
      2: { halign: 'center', cellWidth: 22 },
      3: { halign: 'left', cellWidth: 22 },
      4: { halign: 'left', cellWidth: 35 },
      5: { halign: 'center', cellWidth: 12 },
      6: { halign: 'center', cellWidth: 20 },
      7: { halign: 'center', cellWidth: 14 },
    },
    margin: { left: margin, right: margin },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 10;
  yPosition = addDeclarationAndSignature(doc, yPosition);
  addFooter(doc);

  return doc;
};

const generateStaffDepartmentReport = async (data: ReportData): Promise<jsPDF> => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const margin = 15;

  let yPosition = margin;
  const deptName = data.filters.department || 'All Departments';
  yPosition = await addHeader(doc, `STAFF USER REPORT - ${deptName.toUpperCase()}`, yPosition);

  const staffUsers = filterUsers(
    data.users.filter((u) => u.role !== 'student'),
    data.filters
  );

  yPosition = addMetadata(doc, data, yPosition, {
    'Total Staff:': staffUsers.length.toString(),
  });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 51, 102);
  doc.text('Staff Details', margin, yPosition);
  yPosition += 5;

  const tableData = staffUsers.map((user, index) => [
    (index + 1).toString(),
    user.name,
    user.username,
    getRoleDisplayName(user.role),
    user.department || '—',
    user.email,
    formatDate(user.createdAt),
  ]);

  autoTable(doc, {
    startY: yPosition,
    head: [['Sr.', 'Staff Name', 'Username', 'Designation', 'Department', 'Email', 'Joined Date']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 51, 102],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [0, 0, 0],
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 10 },
      1: { halign: 'left', cellWidth: 32 },
      2: { halign: 'left', cellWidth: 25 },
      3: { halign: 'center', cellWidth: 28 },
      4: { halign: 'center', cellWidth: 25 },
      5: { halign: 'left', cellWidth: 35 },
      6: { halign: 'center', cellWidth: 20 },
    },
    margin: { left: margin, right: margin },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 10;
  yPosition = addDeclarationAndSignature(doc, yPosition);
  addFooter(doc);

  return doc;
};

const generateRoleWiseReport = async (data: ReportData): Promise<jsPDF> => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const margin = 15;

  let yPosition = margin;
  const roleName = data.filters.role ? getRoleDisplayName(data.filters.role) : 'All Roles';
  yPosition = await addHeader(doc, `${roleName.toUpperCase()} USER REPORT`, yPosition);

  const filteredUsers = filterUsers(data.users, data.filters);

  yPosition = addMetadata(doc, data, yPosition, {
    'Total Users:': filteredUsers.length.toString(),
  });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 51, 102);
  doc.text('User Details', margin, yPosition);
  yPosition += 5;

  const tableData = filteredUsers.map((user, index) => {
    const activity = data.activities.find((a) => a.userId === user.id);
    return [
      (index + 1).toString(),
      user.name,
      user.username,
      user.department || '—',
      user.email,
      formatDate(user.createdAt),
      activity?.accountStatus || 'Inactive',
    ];
  });

  autoTable(doc, {
    startY: yPosition,
    head: [['Sr.', 'Name', 'Username', 'Department', 'Email', 'Joined Date', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 51, 102],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [0, 0, 0],
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 10 },
      1: { halign: 'left', cellWidth: 32 },
      2: { halign: 'left', cellWidth: 25 },
      3: { halign: 'center', cellWidth: 25 },
      4: { halign: 'left', cellWidth: 38 },
      5: { halign: 'center', cellWidth: 20 },
      6: { halign: 'center', cellWidth: 15 },
    },
    margin: { left: margin, right: margin },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 10;
  yPosition = addDeclarationAndSignature(doc, yPosition);
  addFooter(doc);

  return doc;
};

const generateLoginActivityReport = async (data: ReportData): Promise<jsPDF> => {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const margin = 15;

  let yPosition = margin;
  yPosition = await addHeader(doc, 'LOGIN & ACTIVITY SESSION REPORT', yPosition);

  const filteredUsers = filterUsers(data.users, data.filters);

  yPosition = addMetadata(doc, data, yPosition, {
    'Total Users:': filteredUsers.length.toString(),
  });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 51, 102);
  doc.text('User Activity Details', margin, yPosition);
  yPosition += 5;

  const tableData = filteredUsers.map((user, index) => {
    const activity = data.activities.find((a) => a.userId === user.id);
    const lastSession =
      activity?.sessions && activity.sessions.length > 0
        ? activity.sessions[activity.sessions.length - 1]
        : null;

    return [
      (index + 1).toString(),
      user.name,
      getRoleDisplayName(user.role),
      user.department || '—',
      activity?.lastLogin ? formatDateTime(activity.lastLogin) : 'Never',
      formatDuration(lastSession?.duration),
      activity?.totalLogins?.toString() || '0',
      activity?.accountStatus || 'Inactive',
    ];
  });

  autoTable(doc, {
    startY: yPosition,
    head: [
      [
        'Sr.',
        'Name',
        'Role',
        'Department',
        'Last Login',
        'Session Duration',
        'Total Logins',
        'Status',
      ],
    ],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 51, 102],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [0, 0, 0],
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 10 },
      1: { halign: 'left', cellWidth: 40 },
      2: { halign: 'center', cellWidth: 25 },
      3: { halign: 'center', cellWidth: 30 },
      4: { halign: 'center', cellWidth: 40 },
      5: { halign: 'center', cellWidth: 25 },
      6: { halign: 'center', cellWidth: 20 },
      7: { halign: 'center', cellWidth: 18 },
    },
    margin: { left: margin, right: margin },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 10;
  yPosition = addDeclarationAndSignature(doc, yPosition);
  addFooter(doc);

  return doc;
};

const generateDepartmentConsolidatedReport = async (data: ReportData): Promise<jsPDF> => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  let yPosition = margin;
  yPosition = await addHeader(doc, 'DEPARTMENT-WISE CONSOLIDATED REPORT', yPosition);

  const filteredUsers = filterUsers(data.users, data.filters);
  const departments = [...new Set(filteredUsers.map((u) => u.department).filter(Boolean))].sort();

  yPosition = addMetadata(doc, data, yPosition, {
    'Total Departments:': departments.length.toString(),
    'Total Users:': filteredUsers.length.toString(),
  });

  departments.forEach((dept) => {
    if (!dept) return;

    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = margin;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(0, 51, 102);
    doc.text(`Department: ${dept}`, margin, yPosition);
    yPosition += 6;

    const deptUsers = filteredUsers.filter((u) => u.department === dept);
    const students = deptUsers.filter((u) => u.role === 'student');
    const staff = deptUsers.filter((u) => u.role !== 'student');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.text('Students', margin + 5, yPosition);
    yPosition += 5;

    if (students.length > 0) {
      const studentData = students.map((user, index) => [
        (index + 1).toString(),
        user.name,
        user.username,
        user.email,
        formatDate(user.createdAt),
      ]);

      autoTable(doc, {
        startY: yPosition,
        head: [['Sr.', 'Name', 'Username', 'Email', 'Joined Date']],
        body: studentData,
        theme: 'grid',
        headStyles: {
          fillColor: [0, 51, 102],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 7,
          halign: 'center',
        },
        bodyStyles: {
          fontSize: 7,
          textColor: [0, 0, 0],
        },
        columnStyles: {
          0: { halign: 'center', cellWidth: 10 },
          1: { halign: 'left', cellWidth: 35 },
          2: { halign: 'left', cellWidth: 30 },
          3: { halign: 'left', cellWidth: 45 },
          4: { halign: 'center', cellWidth: 25 },
        },
        margin: { left: margin + 5, right: margin },
      });

      yPosition = (doc as any).lastAutoTable.finalY + 5;
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.text('No students found', margin + 10, yPosition);
      yPosition += 5;
    }

    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = margin;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.text('Staff', margin + 5, yPosition);
    yPosition += 5;

    if (staff.length > 0) {
      const staffData = staff.map((user, index) => [
        (index + 1).toString(),
        user.name,
        getRoleDisplayName(user.role),
        user.email,
        formatDate(user.createdAt),
      ]);

      autoTable(doc, {
        startY: yPosition,
        head: [['Sr.', 'Name', 'Designation', 'Email', 'Joined Date']],
        body: staffData,
        theme: 'grid',
        headStyles: {
          fillColor: [0, 51, 102],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 7,
          halign: 'center',
        },
        bodyStyles: {
          fontSize: 7,
          textColor: [0, 0, 0],
        },
        columnStyles: {
          0: { halign: 'center', cellWidth: 10 },
          1: { halign: 'left', cellWidth: 40 },
          2: { halign: 'center', cellWidth: 30 },
          3: { halign: 'left', cellWidth: 45 },
          4: { halign: 'center', cellWidth: 25 },
        },
        margin: { left: margin + 5, right: margin },
      });

      yPosition = (doc as any).lastAutoTable.finalY + 8;
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.text('No staff found', margin + 10, yPosition);
      yPosition += 8;
    }
  });

  yPosition = addDeclarationAndSignature(doc, yPosition);
  addFooter(doc);

  return doc;
};

export const generateAdvancedUserReport = async (data: ReportData): Promise<void> => {
  let doc: jsPDF;

  switch (data.reportType) {
    case 'all_users':
      doc = await generateAllUsersReport(data);
      break;
    case 'students_department':
      doc = await generateStudentsDepartmentReport(data);
      break;
    case 'staff_department':
      doc = await generateStaffDepartmentReport(data);
      break;
    case 'department_consolidated':
      doc = await generateDepartmentConsolidatedReport(data);
      break;
    case 'role_wise':
      doc = await generateRoleWiseReport(data);
      break;
    case 'login_activity':
      doc = await generateLoginActivityReport(data);
      break;
    default:
      throw new Error('Invalid report type');
  }

  const timestamp = new Date().toISOString().split('T')[0].replace(/-/g, '');
  const timeStr = new Date()
    .toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true })
    .replace(/:/g, '-')
    .replace(/ /g, '');

  let fileName = `User_Report_${timestamp}_${timeStr}.pdf`;

  if (data.reportType === 'students_department' && data.filters.department) {
    fileName = `Student_Report_${data.filters.department}_${timestamp}_${timeStr}.pdf`;
  } else if (data.reportType === 'staff_department' && data.filters.department) {
    fileName = `Staff_Report_${data.filters.department}_${timestamp}_${timeStr}.pdf`;
  } else if (data.reportType === 'role_wise' && data.filters.role) {
    fileName = `${getRoleDisplayName(data.filters.role)}_Report_${timestamp}_${timeStr}.pdf`;
  } else if (data.reportType === 'login_activity') {
    fileName = `Login_Activity_Report_${timestamp}_${timeStr}.pdf`;
  } else if (data.reportType === 'department_consolidated') {
    fileName = `Department_Consolidated_Report_${timestamp}_${timeStr}.pdf`;
  }

  doc.save(fileName);
};
