import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { User, UserActivity } from '@/types';

const DKTE_LOGO_URL = 'https://miaoda-conversation-file.s3cdn.medo.dev/user-845wqo7mn94w/conv-845wum9wqhog/20251210/file-852rchre4v0g.png';

interface UserReportData {
  users: User[];
  activities: UserActivity[];
  generatedBy: string;
}

const loadImageAsBase64 = async (url: string): Promise<string> => {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error('Error loading image:', error);
    return '';
  }
};

const formatDateTime = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
};

const formatDate = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
};

const getRoleDisplayName = (role: string): string => {
  const roleNames: Record<string, string> = {
    admin: 'Administrator',
    student: 'Student',
    teacher: 'Teacher',
    hod: 'HOD',
    library: 'Library',
    accounts: 'Accounts',
    scholarship: 'Scholarship',
    student_section: 'Student Section',
    hostel_bus: 'Hostel/Bus',
    tpo: 'Training & Placement',
    exam_cell: 'Exam Cell',
  };
  return roleNames[role] || role;
};

const formatDuration = (minutes?: number): string => {
  if (!minutes) return 'N/A';
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  if (hours > 0) {
    return `${hours} hr ${mins} min`;
  }
  return `${mins} min`;
};

const getRoleSortOrder = (role: string): number => {
  const order: Record<string, number> = {
    admin: 1,
    hod: 2,
    teacher: 3,
    library: 4,
    accounts: 5,
    scholarship: 6,
    student_section: 7,
    hostel_bus: 8,
    tpo: 9,
    exam_cell: 10,
    student: 11,
  };
  return order[role] || 99;
};

export const generateUserReportPDF = async (data: UserReportData): Promise<void> => {
  const { users, activities, generatedBy } = data;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  let yPosition = margin;

  try {
    const logoBase64 = await loadImageAsBase64(DKTE_LOGO_URL);
    if (logoBase64) {
      const logoWidth = 50;
      const logoHeight = 13.4;
      const logoX = (pageWidth - logoWidth) / 2;
      doc.addImage(logoBase64, 'PNG', logoX, yPosition, logoWidth, logoHeight);
      yPosition += logoHeight + 5;
    }
  } catch (error) {
    console.error('Error adding logo:', error);
    yPosition += 5;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(0, 51, 102);
  const collegeName = "DKTE SOCIETY'S YASHWANTRAO CHAVAN POLYTECHNIC";
  doc.text(collegeName, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 7;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0, 102, 51);
  doc.text('USER MANAGEMENT & ACTIVITY REPORT', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 3;

  doc.setDrawColor(0, 102, 51);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);

  const metaData = [
    ['Generated By:', generatedBy],
    ['Generated On:', formatDateTime(new Date().toISOString())],
    ['Total Users:', users.length.toString()],
  ];

  const startX = margin;
  const labelWidth = 35;

  metaData.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, startX, yPosition);
    doc.setFont('helvetica', 'normal');
    doc.text(value, startX + labelWidth, yPosition);
    yPosition += 5;
  });

  yPosition += 3;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 51, 102);
  doc.text('User Information', margin, yPosition);
  yPosition += 5;

  const sortedUsers = [...users].sort((a, b) => {
    const orderA = getRoleSortOrder(a.role);
    const orderB = getRoleSortOrder(b.role);
    if (orderA !== orderB) return orderA - orderB;
    return a.name.localeCompare(b.name);
  });

  const userTableData = sortedUsers.map((user, index) => {
    return [
      (index + 1).toString(),
      user.name,
      user.username,
      getRoleDisplayName(user.role),
      user.department || '—',
      user.email,
      formatDate(user.createdAt),
    ];
  });

  autoTable(doc, {
    startY: yPosition,
    head: [['Sr.', 'Full Name', 'Username', 'Role', 'Department', 'Email', 'Joined Date']],
    body: userTableData,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 51, 102],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [0, 0, 0],
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 10 },
      1: { halign: 'left', cellWidth: 30 },
      2: { halign: 'left', cellWidth: 25 },
      3: { halign: 'center', cellWidth: 25 },
      4: { halign: 'center', cellWidth: 25 },
      5: { halign: 'left', cellWidth: 35 },
      6: { halign: 'center', cellWidth: 20 },
    },
    margin: { left: margin, right: margin },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 10;

  if (yPosition > pageHeight - 60) {
    doc.addPage();
    yPosition = margin;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 51, 102);
  doc.text('Login & Activity Session Details', margin, yPosition);
  yPosition += 5;

  sortedUsers.forEach((user, index) => {
    const activity = activities.find((a) => a.userId === user.id);

    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = margin;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.text(`${index + 1}. ${user.name} (@${user.username})`, margin, yPosition);
    yPosition += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(60, 60, 60);

    const activityDetails = [
      `Last Login: ${activity?.lastLogin ? formatDateTime(activity.lastLogin) : 'Never'}`,
      `Last Logout: ${activity?.lastLogout ? formatDateTime(activity.lastLogout) : 'N/A'}`,
      `Total Logins: ${activity?.totalLogins || 0}`,
      `Account Status: ${activity?.accountStatus || 'Inactive'}`,
    ];

    if (activity?.sessions && activity.sessions.length > 0) {
      const lastSession = activity.sessions[activity.sessions.length - 1];
      activityDetails.push(`Session Duration: ${formatDuration(lastSession.duration)}`);
    } else {
      activityDetails.push('Session Duration: N/A');
    }

    const detailX = margin + 5;
    activityDetails.forEach((detail) => {
      doc.text(detail, detailX, yPosition);
      yPosition += 4;
    });

    yPosition += 3;
  });

  if (yPosition > pageHeight - 60) {
    doc.addPage();
    yPosition = margin;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 51, 102);
  doc.text('System Activity Summary', margin, yPosition);
  yPosition += 6;

  const totalActive = activities.filter((a) => a.accountStatus === 'active').length;
  const totalStudents = users.filter((u) => u.role === 'student').length;
  const totalAdmins = users.filter((u) => u.role === 'admin').length;
  const totalHODs = users.filter((u) => u.role === 'hod').length;

  const mostActiveUser = activities.reduce(
    (max, a) => (a.totalLogins > (max?.totalLogins || 0) ? a : max),
    activities[0]
  );
  const mostActiveUserName = users.find((u) => u.id === mostActiveUser?.userId)?.name || 'N/A';

  const allSessions = activities.flatMap((a) => a.sessions);
  const sessionsWithDuration = allSessions.filter((s) => s.duration);
  const avgDuration =
    sessionsWithDuration.length > 0
      ? Math.floor(
          sessionsWithDuration.reduce((sum, s) => sum + (s.duration || 0), 0) /
            sessionsWithDuration.length
        )
      : 0;

  const summaryData = [
    ['Total Active Users:', totalActive.toString()],
    ['Total Students:', totalStudents.toString()],
    ['Total Admins:', totalAdmins.toString()],
    ['Total HODs:', totalHODs.toString()],
    ['Most Active User:', mostActiveUserName],
    ['Average Session Duration:', formatDuration(avgDuration)],
  ];

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);

  summaryData.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, margin + 5, yPosition);
    doc.setFont('helvetica', 'normal');
    doc.text(value, margin + 60, yPosition);
    yPosition += 5;
  });

  yPosition += 5;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(0, 51, 102);
  doc.text('Declaration', margin, yPosition);
  yPosition += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0);
  const declarationText =
    'This report is generated from the system database and reflects real-time user and activity data as of the generated date.';
  const splitDeclaration = doc.splitTextToSize(declarationText, pageWidth - 2 * margin);
  doc.text(splitDeclaration, margin, yPosition);

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    const footerY = pageHeight - 10;
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);

    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text(
      'This is a system-generated document and does not require a physical signature.',
      pageWidth / 2,
      footerY,
      { align: 'center' }
    );

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, footerY + 3, { align: 'right' });
  }

  const timestamp = new Date().toISOString().split('T')[0].replace(/-/g, '');
  const fileName = `All_Users_Report_${timestamp}.pdf`;
  doc.save(fileName);
};
